<?php
$title = 'Agregar nuevo plato';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/plato/agregar-plato?id='.$this->id,
    'method' => 'post',
    'class'=>'form-horizontal'
));

$form->prepare();
echo $this->form()->openTag($form);
?>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php echo $this->formHidden($form->get('in_id'));?>
<?php echo $this->formHidden($form->get('Ta_usuario_in_id'));?>
<?php echo $this->formHidden($form->get('Ta_puntaje_in_id'));?>  
<div class="row-fluid">
<div class="control-group span6"><?php echo $this->formRow($form->get('va_nombre'));?></div>
<div class="control-group span6"><?php echo $this->formRow($form->get('va_imagen'));?></div>
</div>
<div class="row-fluid">
<div class="control-group span5"><?php echo $this->formRow($form->get('tx_descripcion'));?></div>
<div class="control-group span3"><?php echo $this->formRow($form->get('va_precio'));?></div>
<div class="control-group span3"><?php echo $this->formRow($form->get('Ta_tipo_plato_in_id'));?></div>
<div class="control-group span3 over-promocion"><?php echo $this->formRow($form->get('va_promocion'));?></div>
<div class="control-group span3 agregar-campo " style="display:none;"><?php echo $this->formRow($form->get('va_otros'));?></div>

</div>
<div class="row-fluid">
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div></div><?php echo $this->form()->closeTag();?> 
</div>