<div class="span10" id="flip-scroll">
<table class="table table-bordered table-hover" id="tabla-platos">
    <thead class="cf">  
        <tr>
            <th>N°</th>


            <th>Nombre</th>
             <th>Numero comentarios</th>
<!--             <th>Puntaje</th>-->
             <th>Promedio</th>

        </tr>
    </thead>
    
        <?php $count = 1;
    foreach ($this->lista  as $list) :
        ?>
        <tr >
            <td><?php echo $count++ ?></td>
            <td><?php echo $this->escapeHtml($list->va_nombre); ?></td>
            <td><?php echo $this->escapeHtml($list->NumeroComentarios); ?></td> 
<!--            <td><?php echo $this->escapeHtml($list->ta_puntaje_in_id); ?></td> -->
            <td><?php echo $this->escapeHtml($list->Promedio); ?></td>
        </tr>

<?php endforeach; ?>
    
</table>
</div>