<?php if ($this->pageCount): ?>
<div class="pagination ">
<!-- Previous page link -->
<ul>
<?php if (isset($this->previous)): ?>
  <li><a href='<?php echo $this->variable;?>page=<?php echo $this->previous?>'> « Anterior  </a> </li>
<?php else: ?>
  <li class="disabled"> <a href="#">« Anterior</a></li> 
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href='<?php echo $this->variable;?>page=<?php echo $page; ?>'><?php echo $page; ?>
    </a></li> 
  <?php else: ?>
    <li class="active"><a href="#"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li><a class="next" href='<?php echo $this->variable;?>page=<?php echo $this->next?>'> Siguiente » </a></li>
<?php else: ?>
  <li class="disabled"><a href="#">Siguiente »</a></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>