<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Local\Module'                        => __DIR__ . '/Module.php',
    'Local\Controller\IndexController' => __DIR__ . '/src/Local/Controller/IndexController.php',
    'Local\Framework\TestCase'        => __DIR__ . '/tests/Local/Framework/TestCase.php',
    'Local\SampleTest'                => __DIR__ . '/tests/Local/SampleTest.php',
);