<script type="text/javascript" src="<?php echo $this->host('ruta')?>/js/jquery.validate.min.js"></script>

        <?php if($this->mensaje[0]){?>
        <div class="row-fluid">
        	<div class="alert alert-success alert-message" style="margin-bottom:0;margin-top:20px;">
        		<button type="button" class="close" data-dismiss="alert">×</button>
        		<?php echo $this->mensaje[0];?>
        	</div>
        </div>
		<?php }?>
		<div class="row-fluid">
			<div class="span12 recuperacion group-sidebar">
			<?php 
			$form = $this->form;
			$form->setAttributes(array(
			    'action' => $this->url.'/cambio-contrasena?value='.$this->password,
			    'method' => 'post',
			    'class'=>'span12 form-crear-usuario',
			    'id'=>'registro'
			));
			$form->prepare();
			echo $this->form()->openTag($form);
			
			?>
					<h3>Nueva clave ListaDelSabor</h3>
					<div class="row-fluid">
						<label for="pass">Contraseña:</label>
						<?php echo $this->formrow($form->get('va_contrasena'))?>
					</div>
					<div class="row-fluid">
						<label for="pass">Repita contraseña:</label>
						<?php echo $this->formrow($form->get('verificar_contrasena'))?>
					</div>
		            <div class="row-fluid">
		             <?php echo $this->formSubmit($form->get('submit'));?>
		            </div>
		            <?php echo $this->form()->closeTag();?>
			</div>
		</div>


<script type="text/javascript">
	$(document).ready(function(){
		$(".alert-message").alert();
        window.setTimeout(function() { $(".alert-message").alert('close'); }, 15000);

		$("#registro").validate({
            rules: {
                va_contrasena:{
	                required : true,
	                minlength:8             
	            },
	            verificar_contrasena:{
	                required : true,
	                equalTo: "#va_contrasena",
	                minlength:8               
	            }
            },
            messages: {
              	va_contrasena: {
	                required : "Por favor ingrese su contraseña",
	                minlength:"Por favor ingrese una contraseña de 8 caracteres a mas"
	            },
	            verificar_contrasena: {
	                required : "Por favor repita la contraseña",            
	                minlength:"Por favor ingrese una contraseña de 8 caracteres a mas",
	                equalTo : "Por favor ingrese la misma contraseña"
	            }
            }
        });
	});
</script>