<?php
$title = 'Modificar  usuario';
$this->headTitle($title);
?>
<div class="span8">
<?php
$form = $this->form;
$form->setAttributes(array(
    'action' => $this->url.'/usuario/index/editarusuario?id='.$this->in_id,
    'method' => 'post',
    'in_id'   =>$this->in_id,
));
$form->prepare();
echo $this->form()->openTag($form);
?><legend><?php echo $this->escapeHtml($title); ?></legend>
<?php
echo $this->formHidden($form->get('in_id'));
?>
<div class="control-group span5 "><?php echo $this->formRow($form->get('va_nombre'));?></div><?php
?><div class="control-group span5"><?php echo $this->formRow($form->get('va_apellidos'));?></div ><?php
?><div class="control-group span5"><?php echo $this->formRow($form->get('va_email'));?></div><?php
?><div class="control-group span5"><label class="control-label">Password</label>  <input class="span10" id="va_contrasenia" type="password" name="va_contrasenia" value="<?php  echo $this->pass ?>"></div>
 <div class="control-group span5"> <label class="control-label">Repita su password</label> <input class="span10" id="va_contrasenia2" type="password" name="va_contrasenia2" value="<?php  echo $this->pass ?>"></div> <?php
?><div class="control-group span5"><?php echo $this->formRow($form->get('Ta_rol_in_id'));?></div><?php
?><div class="control-group span12"><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag();  ?>
</div>

