    <div class="span12">
      <div class="span12"> 
             <form name='form_busqueda'class="form-search" action='<?php echo $this->basePath(); ?>/usuario/index' method ="post">
             
                 <div class="control-group">
                  <label class="ra radio">
                 <input type='radio' name='listado'  id='nom' value='va_nombre' checked/>Por nombre 
                 </label>
                 <label class="ra radio">    
                <input type='radio' name='listado' id='dire1' value='1'/>Por Administrador
                </label>
                <label class="ra radio">
                <input type='radio' name='listado' id='dire2' value='2'/>Por Editor</label>
                 <input type='text' name='texto' id="texto"/>
                <input type="submit" class="btn" name="submit" value="Buscar">
                </div>
            </div>
            </form>
    </div>
<div class="row-fluid">
<div class="span12" id="flip-scroll">
<table class="table table-bordered table-hover">
    <thead class="cf">  
        <tr>
            <th>#</th> 
            <th>N°</th>
            <th>Status</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Email</th>
            <th>Rol</th>
            <th>Operaciones</th>
        </tr>
    </thead>

    <?php $count = 1;
    foreach ($this->usuarios as $usuario) :// foreach ($this->paginator as $usuario) :
        ?>
        <tr id"<?php echo $this->escapeHtml($usuario->in_id); ?>">
            <td><?php echo $count++ ?></td>
    <?php if ($usuario->en_estado == 'activo') { ?>
                <td><input data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" type="checkbox" class="check" checked="checked"> </td>
                <td><span id="la<?php echo $this->escapeHtml($usuario->in_id); ?>" class='label label-success'> <?php echo $this->escapeHtml($usuario->en_estado); ?></span></td>
    <?php } else { ?>
                <td><input data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" type="checkbox" class="check"> </td>
                <td><span id="la<?php echo $this->escapeHtml($usuario->in_id); ?>" class='label label-important'> <?php echo $this->escapeHtml($usuario->en_estado); ?></span></td>
    <?php } ?>
            <td><?php echo $this->escapeHtml($usuario->va_nombre); ?></td> 
            <td><?php echo $this->escapeHtml($usuario->va_apellidos); ?></td>
            <td><?php echo $this->escapeHtml($usuario->va_email); ?></td>
            <td><?php echo $this->escapeHtml($usuario->va_nombre_rol); ?></td>
            <td><a data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" href="<?php echo $this->basePath();?>/usuario/index/editarusuario?id=<?php echo $usuario->in_id;?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Edit </a>
            <a name="<?php echo $this->escapeHtml($usuario->va_nombre); ?>" data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" href="#" class='eli btn btn-danger'><i class='icon-trash icon-white'></i>Delete</a> </td>
        </tr>

<?php endforeach; ?>
<!--        <div style="clear: both;">
<?php (count($this->paginator)> 0)?$this->paginationControl($this->paginator, 'Sliding', 'usuario/index/paginador.phtml'):""; ?>
</div>-->
<!--  ------------------------PAGINADOR------------------------------------------------>
  


<!-- -------------------------fin---------------------------------------->
</table>
</div>
</div>
<div class="span4">
  
    <div class="modal small hide fade" id="eli-user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Confirmación de Eliminación</h3>
        </div>
        <div class="modal-body">
            <p class="error-text"><strong><label id="verusuario"></label></strong></p>

        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            <button class="btn btn-danger" id="delete">Eliminar</button>
        </div>
    </div>
    
</div>

