
<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Restaurante\Module'                        => __DIR__ . '/Module.php',
    'Restaurante\Controller\IndexController' => __DIR__ . '/src/Restaurante/Controller/IndexController.php',
    'Restaurante\Framework\TestCase'        => __DIR__ . '/tests/Restaurante/Framework/TestCase.php',
    'Restaurante\SampleTest'                => __DIR__ . '/tests/Restaurante/SampleTest.php',
);