 <style type="text/css">
table,tr,td,th
{  
border: 1px solid #000; 
border-collapse: collapse;
text-align: center;
}
     </style>
     <br>
     <br>
 <?php  
header("Pragma: public");
header("Cache-Control: no-store, no-cache, must-revalidate");
header("Cache-Control: pre-check=0, post-check=0, max-age=0");
header("Pragma: no-cache");
header("Expires: 0");
header("Content-Transfer-Encoding: none");
header("Content-Type: application/vnd.ms-excel;");
header("Content-type: application/x-msexcel");
header("Content-Disposition: attachment; filename=Comentarios_".date('Ymd').".xls");
    echo("<table>");
    echo("<tr style='font-weight: bold;'>");
    echo("<td>Id</td>");
    echo("<td>Estado</td>");
    echo("<td>Comentario</td>");
    echo("<td>Puntaje</td>");
    echo("<td>Plato</td>");
    echo("<td>Usuario</td>");
    if($this->comentarios)
        { 
                foreach($this->comentarios as $fila)
                {   
                ?>
                <tr>
                <td width="85"><?php echo $fila->in_id ?></td>
                <td width="100"><?php echo $fila->en_estado ?></td>
                <td width="200"><?php echo $fila->tx_descripcion ?></td>
                <td width="200"><?php echo $fila->va_valor ?></td>
                <td width="200"><?php echo $fila->va_nombre ?></td>
                <td width="200"><?php echo $fila->va_nombre_cliente ?></td>
                </tr>
                <?php 
                }               
         } 
                ?>
  </table>