
<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Usuario\Module'                        => __DIR__ . '/Module.php',
    'Usuario\Controller\IndexController' => __DIR__ . '/src/Usuario/Controller/IndexController.php',
    'Usuario\Controller\ComentariosController' => __DIR__ . '/src/Usuario/Controller/ComentariosController.php',
    'Usuario\Framework\TestCase'        => __DIR__ . '/tests/Usuario/Framework/TestCase.php',
    'Usuario\SampleTest'                => __DIR__ . '/tests/Usuario/SampleTest.php',
);