<?php
header('Content-Type: text/html; charset=utf-8');
$limit = 10;
$query = isset($_REQUEST['q']) ? $_REQUEST['q'] : false;
$results = false;
if ($query)
{ 
  require './vendor/SolrPhpClient/Apache/Solr/Service.php';
  $solr = new Apache_Solr_Service('localhost', 8983, '/solr/');
  if (get_magic_quotes_gpc() == 1)
  {
    $query = stripslashes($query);
  }
  try
  {
    $results = $solr->search($query, 0, $limit);

  }
  catch (Exception $e)
  {
  
        echo("<html><head><title>SEARCH EXCEPTION</title><body><pre>{$e->__toString()}</pre></body></html>");
             
  }
}

?>

    <form  accept-charset="utf-8" method="get">
      <label for="q">BUSCAR:</label>
      <input id="q" name="q" type="text" value="<?php echo htmlspecialchars($query, ENT_QUOTES, 'utf-8'); ?>"/>
      <input type="submit"/>
    </form>
<?php


if ($results)
{
  $total = (int) $results->response->numFound;
  $start = min(1, $total);
  $end = min($limit, $total);
?>
    <div>Resultados <?php echo $start; ?> - <?php echo $end;?> de <?php echo $total; ?>:</div>  
    <ol>
    
<?php
 
    foreach ($results->response->docs as $doc)
    {
?> <li>
          <table style="border: 1px solid black; text-align: left">
           <tr><td>id: <?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?></td> </tr>
           <tr><td>nombre: <?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></td></tr>
           <tr><td>razon_social: <?php echo htmlspecialchars($doc->razon_social, ENT_QUOTES, 'utf-8'); ?></td></tr>
           <tr><td>ruc: <?php echo htmlspecialchars($doc->ruc, ENT_QUOTES, 'utf-8'); ?></td></tr>
           </table>
      </li>
<?php
    }
?>
       

    </ol>
<?php
}  else 
     {
    echo 'no existen resultados para su busqueda';   
     }
?>
