<?php
$title = 'Editar nuevo banner';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/restaurante/index/editarbanner',
    'method' => 'post',
    'class'=>'form-horizontal'
));
$form->prepare();

echo $this->form()->openTag($form);
?><legend><?php echo $this->escapeHtml($title); ?></legend>
<?php
echo $this->formHidden($form->get('in_id'));
?>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_nombre'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_imagen'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_url'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('in_orden'));?></div><?php?>
<div class="control-group span12 "><?php echo $this->formSubmit($form->get('submit'));?></div><?php echo $this->form()->closeTag();?> 
</div>


