  <!--   <div class="span2">
    <div class="btn-group" data-toggle="buttons-radio">
  <a  class="btn" href="<?php echo $this->basePath();?>/restaurante/index/agregarrestaurante">AGREGAR RESTAURANTE</a>
    </div>
    </div> -->
    <div class="span12">
   
<form name='form_busqueda'class="form-search" action='<?php echo $this->basePath(); ?>/restaurante/index/index' method ="get">
   <div class="control-group span3">
   <label class="ra radio">    
   POR TIPO :
   </label>
   <SELECT NAME="comida" SIZE="1" class="span12">
   <OPTION VALUE="">seleccione:</OPTION>
      <?php  foreach ($this->comida as $comida) : ?>
     <OPTION VALUE="<?php echo $comida['in_id']; ?>"><?php echo $comida['va_nombre_tipo']; ?></OPTION>
     <?php endforeach; ?>
   </SELECT>
   </div>
   <div class="control-group span3">
   <label class="ra radio">    
   POR ESTADO :
   </label>
   <SELECT NAME="estado" SIZE="1" class="span12">
   <OPTION VALUE="">seleccione:</OPTION>
   <OPTION VALUE="activo">activo</OPTION>
   <OPTION VALUE="desactivo">desactivo</OPTION>
   </SELECT>
   </div>
   <div class="control-group span3">
    <label class="ra radio">POR NOMBRE: </label>
    <input type='text' name='texto' id="texto" class="span12" value="<?php if($this->texto){echo $this->texto;}else{}?>">   
    </div>
    <div class="control-group span3">
      <input type="submit" class="btn boton" name="submit" value="BUSCAR">
    </div>
    </form>  
    </div>    
<div class="row-fluid">
<div class="span12" id="flip-scroll">
<table class="table table-bordered table-hover">
    <thead class="cf">  
        <tr>
          <th>#</th> 
            <th>N°</th>
            <th>Status</th>
            <th>Nombre</th>
            <th>Razon Social</th>
           <!--  <th>Web</th> -->
            <th>Especialidad</th>
            <th>Operaciones</th>
        </tr>
    </thead>
    <?php $count = 1;
    foreach ($this->restaurante  as $usuario) :// foreach ($this->paginator as $usuario) :
        ?>
        <tr id="<?php echo $this->escapeHtml($usuario->in_id); ?>">
            <td><?php echo $count++ ?></td>
    <?php if ($usuario->en_estado == 'activo') { ?>
                <td><input data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" type="checkbox" class="check_rest" checked="checked"> </td>
                <td><span id="la<?php echo $this->escapeHtml($usuario->in_id); ?>" class='label label-success'> <?php echo $this->escapeHtml($usuario->en_estado); ?></span></td>
                    <td><a href="<?php echo $this->basePath();?>/local/index/index/<?php echo $usuario->in_id;?>"><?php echo $this->escapeHtml($usuario->va_nombre); ?></a></td>
                    <td><?php echo $this->escapeHtml($usuario->va_razon_social); ?></td>
            <!-- <td><?php echo $this->escapeHtml($usuario->va_web); ?></td> -->
            <td><?php echo $this->escapeHtml($usuario->va_nombre_tipo); ?></td>
             <td><a data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" href="<?php echo $this->basePath();?>/restaurante/index/editarrestaurante/<?php echo $usuario->in_id;?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Editar </a>
           <a name="<?php echo $this->escapeHtml($usuario->va_nombre); ?>" data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" href="/local/index/agregarlocal?id=<?php echo $usuario->in_id;?>" class='listar btn btn-inverse'><i class='icon-tasks icon-white'></i>LOCAL</a> </td>
    <?php } else { ?>
                <td><input data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" type="checkbox" class="check_rest"> </td>
                <td><span id="la<?php echo $this->escapeHtml($usuario->in_id); ?>" class='label label-important'> <?php echo $this->escapeHtml($usuario->en_estado); ?></span></td>
                     <td><a><?php echo $this->escapeHtml($usuario->va_nombre); ?></a></td>
                    <td><?php echo $this->escapeHtml($usuario->va_razon_social); ?></td>
            <!-- <td><?php echo $this->escapeHtml($usuario->va_web); ?></td> -->
            <td><?php echo $this->escapeHtml($usuario->va_nombre_tipo); ?></td>
             <td><a data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" href="<?php echo $this->basePath();?>/restaurante/index/editarrestaurante/<?php echo $usuario->in_id;?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Editar </a>
           </td>
    <?php } ?>
         
        
           
        </tr>

<?php endforeach; ?>
</table>
    <?php if($this->estado) 
    {$estado=$this->estado;}
//    else{
// $estado='activo'; }?>
     <?php echo (count($this->restaurante)> 0)?$this->paginationControl($this->restaurante, 'Sliding', 'restaurante/index/paginador.phtml',array('variable'=>'/restaurante/index/index?','estado'=>$estado,'comida'=>$this->comid)):""; ?>
</div>
</div>

