
    <div class="span12">
 
    </div>    
<div class="row-fluid">
<div class="span12" id="flip-scroll">
<table class="table table-bordered table-hover">
    <thead class="cf">  
        <tr>
          <th>#</th> 
            <th>Nombre</th>
          
        <th>Operaciones</th>
        </tr>
    </thead>
    <?php $count = 1;
    foreach ($this->listabanner  as $listamenu) :
        ?>
      <tr id="<?php echo $this->escapeHtml($listamenu->in_id); ?>">
       <td><?php echo $count++ ?></td>
 
       <td><a href="<?php echo $this->basePath();?>/editar-tag/<?php echo $listamenu->in_id;?>"><?php echo $this->escapeHtml($listamenu->va_nombre); ?></a></td>
          <td><a data-id="<?php echo $this->escapeHtml($listamenu->in_id); ?>" href="<?php echo $this->basePath();?>/editar-tag/<?php echo $listamenu->in_id;?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Editar </a>


                    </tr>
<?php endforeach; ?>
</table>
     <?php echo (count($this->listabanner)> 0)?$this->paginationControl($this->listabanner, 'Sliding', 'platos/index/paginador.phtml',array('variable'=>'/restaurante/index/listadotag?')):""; ?>
</div>
<div class="modal small hide fade" id="eli-local" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Confirmación de Eliminación</h3>
  </div>
  <div class="modal-body">
      <p class="error-text"><strong><label id="verlocal"></label></strong></p>

  </div>
  <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
      <button class="btn btn-danger" id="delete-local-banner">Eliminar</button>
  </div>
</div>

</div>

