<?php


$title = 'Agregar nuevo cliente';
$this->headTitle($title);
?>
<div class="span8">

<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
$form->setAttributes(array(
    'action' => $this->url.'/usuario/cliente/agregarclientes',
    'method' => 'post'
));
$form->prepare();


echo $this->form()->openTag($form);
?><legend><?php echo $this->escapeHtml($title); ?></legend>
<?php
echo $this->formHidden($form->get('in_id'));

?>
<div class="control-group span5 "><?php echo $this->formRow($form->get('va_nombre'));?></div><?php
?><div class="control-group span5"><?php echo $this->formRow($form->get('va_email'));?></div><?php
?><div class="control-group span12"><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag(); ?>
</div>