    <div class="span12">
    <div class="control-group"> 
            <form name='form_busqueda'class="form-search" action='/usuario/cliente/clientes' method ="post">
                    <div class="control-group">
                    <label class="ra radio">Buscar:
                    <input type='text' name='texto' id="texto" placeholder="Nombre,Email" />
                    <input type="submit" class="btn" name="submit" value="Buscar">
                    </div>
            </form>
    </div>
    </div>
<div class="row-fluid">
<div class="span12" id="flip-scroll">       
<table class="table table-bordered table-hover">
    <thead  class="cf">  
        <tr>
            <th>#</th> 
            <th>Nombre del cliente</th>
            <th>Email</th>
        </tr>
    </thead>
    
        <?php $count = 1;
    foreach ($this->clientes  as $cliente) :// foreach ($this->paginator as $usuario) :
        ?>
        <tr id="<?php echo $cliente->in_id; ?>">
            <td><?php echo $count++ ?></td>
            <td><?php echo $cliente->va_nombre_cliente; ?></td> 
            <td><?php echo $cliente->va_email; ?></td>
        </tr>

<?php endforeach; ?>
      
</table>
    <?php echo (count($this->clientes)> 0)?$this->paginationControl($this->clientes, 'Sliding', 'platos/index/paginador.phtml',array('variable'=>'/usuario/cliente/clientes?')):""; ?>
</div>
</div>
<div class="span10" style="padding: 10px 0;">
    <a href='/usuario/cliente/exportarexcel' class="btn" >Exportar Datos </a>
</div>   
