<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Administración Restaurante</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">                         
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/main.css?v'.$this->host('version'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css?v'.$this->host('version')) ?>                          
                                   
    </head>
    <body>  
        
  <div class="contenido"> 
                <?php echo $this->content; ?>
  </div> 
   <script src="<?php echo $this->basePath()?>/js/lib/jquery-1.8.3.min.js?v<?php echo $this->host('version')?>"></script> 
  <script src="<?php echo $this->basePath()?>/js/lib/bootstrap.min.js?v<?php echo $this->host('version')?>"></script>            
    </body>
</html>
    



