 <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
 <script src="<?php echo $this->basePath()?>/js/vendor/gmap3.min.js?v<?php echo $this->host('version')?>"></script> 
<?php
$title = 'Agregar nuevo local';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/local/index/agregarlocal',
    'method' => 'post',
    'class'=>'form-horizontal'
));
$form->prepare();

echo $this->form()->openTag($form);
?><legend><?php echo $this->escapeHtml($title); ?></legend>
<?php
echo $this->formHidden($form->get('in_id'));
?>
<?php
echo $this->formHidden($form->get('ta_restaurante_in_id'));
?>
<h5><?php echo $this->id ;?></h5>
<div class="row-fluid">
<div class="control-group span4"><?php echo $this->formRow($form->get('va_telefono'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_horario'));?></div ><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_horario_opcional'));?></div ><?php?>
</div>
<div class="row-fluid">
<div class="control-group span4"><?php echo $this->formRow($form->get('va_rango_precio'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_dia'));?></div><?php?>
<div class="control-group span4 "><?php echo $this->formRow($form->get('pais'));?></div><?php?>
</div>
<div class="row-fluid">
<div class="control-group span4"><?php echo $this->formRow($form->get('departamento'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('provincia'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('distrito'));?></div><?php?>
</div>
<div class="row-fluid">
<div class="control-group span4" style="height: 126px;overflow: auto;">
  <label for="">Seleccione Servicio que ofrece</label>
  <label class="checkbox inline">
   <?php echo $this->formRow($form->get('servicio'));?> 
  </label>
</div>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_direccion'));?></div>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_direccion_referencia'));?> </div>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_email'));?> </div>  
<div class="control-group span4">
                              <label>Encuentra tu ubicación</label>
                              <div><input type="hidden" maxlength="100" id="address" name="address" class="span5 uneditable-input"/> <input type="button" class="btn btn-danger" id="search" value="BUSCAR EN MAPA" /></div>                                     
                             </div>
</div>
<div class="row-fluid">
<div class="control-group span12" id="mostrar_map">
   <div id='map_canvas' style="height:400px;width:900px;"></div> 
</div>
</div>
<div class="row-fluid">
<div class="control-group span12"><?php echo $this->formSubmit($form->get('submit'));?></div>
</div>
<div class="control-group"><?php echo $this->formRow($form->get('de_latitud'));?></div>
<div class="control-group"><?php echo $this->formRow($form->get('de_longitud'));?></div>
<?php echo $this->form()->closeTag();?> </div> 
</div>

<script>
	$(document).ready(function(){
		var id_r = $('h5').text();
    $('#address').val("");
     $('#ta_restaurante_in_id').val(id_r);

	})
</script>