 <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
 <script src="<?php echo $this->basePath()?>/js/vendor/gmap3.min.js?v<?php echo $this->host('version')?>"></script> 
<?php
$title = 'Editar local';
$this->headTitle($title);
?>

<div class="span12">
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/local/index/editarlocal/'.$this->id_re.'?id='.$this->id,
    'method' => 'post',
    'in_id'   =>$this->id,
));
$form->prepare();



echo $this->form()->openTag($form);
?><legend><?php echo $this->escapeHtml($title); ?></legend>
<?php
echo $this->formHidden($form->get('in_id'));
?>
<?php
echo $this->formHidden($form->get('ta_restaurante_in_id'));
?>


<?php
echo $this->formHidden($form->get('h_pais'));
?>
<?php
echo $this->formHidden($form->get('h_departamento'));
?>
<?php
echo $this->formHidden($form->get('h_provincia'));
?>
<?php
echo $this->formHidden($form->get('h_distrito'));
?>
<h5><?php echo $this->id ;?></h5>
<div class="row-fluid">
<div class="control-group span4"><?php echo $this->formRow($form->get('va_telefono'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_horario'));?></div ><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_horario_opcional'));?></div ><?php?>
</div>
<div class="row-fluid">
<div class="control-group span4"><?php echo $this->formRow($form->get('va_rango_precio'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_dia'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('pais'));?></div><?php?>
</div>
<div class="row-fluid">
<div class="control-group span4"><?php echo $this->formRow($form->get('departamento'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('provincia'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('distrito'));?></div><?php?>
 </div>
<div class="row-fluid">
 <div class="control-group span4" style="height: 126px;overflow: auto;">
  <label for="">Seleccione Servicio que ofrece</label>
  <label id="servicio_local" class="checkbox inline">
  <?php echo $this->formRow($form->get('servicio'));?>
  </label>
</div>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_direccion'));?></div><?php?>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_direccion_referencia'));?> </div>
<div class="control-group span4"><?php echo $this->formRow($form->get('va_email'));?> </div>  
<div class="control-group span3">
               <label>Buscar en el Mapa</label>
               <div><input type="hidden" maxlength="100" id="address" name="address" class="span5 uneditable-input"/> <input type="button" class="btn btn-info" id="search" value="UBICACION" /></div>
                                        
  </div>
</div>
<div class="row-fluid">
<div class="control-group span12" id="mostrar_map" style="display:block;"><div id='map_canvas' style="display:block;height:400px;width:900px;"></div> </div></div>
<div class="row-fluid">
<div class="control-group span12"><?php echo $this->formSubmit($form->get('submit'));?></div></div>
<div class="control-group span5 "><?php echo $this->formRow($form->get('de_latitud'));?></div>
<div class="control-group span5"><?php echo $this->formRow($form->get('de_longitud'));?></div>
<?php echo $this->form()->closeTag();?> </div> 
</div>

<script>
	$(document).ready(function(){
     var value = $("#va_direccion").val();   
     var d = $("#distrito option:selected").text();
     var p = $("#provincia option:selected").text();
     var pa = $("#pais option:selected").text();         
 		  var id_r = $('h5').text();
      var id =$("#id").val();      
      var url3="/local/index/jsonservicios?id=" + id;
    $.getJSON(url3,function(data){              
            $.each(data,function(i,val){
            $(".checkbox").each(function(){ 
              var va = $(this).attr('value');
              console.log(val.ta_servicio_local_in_id);
           if (va==val.ta_servicio_local_in_id ){
                $(this).prop("checked" , true ); 
             } 
             });                       
    });
});
      $('#ta_restaurante_in_id').val(id_r);
       var pais=parseInt($('#pais').val());
         var depa=parseInt($('#h_departamento').val());
         var prov=parseInt($('#h_provincia').val());
         var dis=parseInt($('#h_distrito').val());
      $.getJSON('/local/index/jsondepartamento',function(data){
              $.each(data,function(i,val){              
                $('#departamento').append( "<option value=" + val.in_iddep + ">" + val.ch_departamento + " </option>");
                   $("#departamento" +" option[value=" +depa +"]").attr("selected","selected");                        
          });          
        
      });
    
  
    var url="/local/index/jsonprovincia?iddepa=" + depa;
              $.getJSON(url,function(data){
                  $("#provincia").empty();  
                $.each(data,function(i,val){ 
                                 
                    $('#provincia').append( "<option value=" + val.in_idprov + ">" + val.ch_provincia + " </option>");      $("#provincia" +" option[value=" +prov +"]").attr("selected","selected");                          
                          });  
         });
    var url2="/local/index/jsondistrito?iddepa=" + depa + "&iddpro=" + prov
      $.getJSON(url2,function(data){
         $("#distrito").empty();
        $("#distrito").append("<option value=''>Seleccione</option>");
    $.each(data,function(i,val){  
          
                $('#distrito').append( "<option value=" + val.in_iddis + " >" + val.ch_distrito + " </option>");   
                  $("#distrito" +" option[value=" +dis +"]").attr("selected","selected");
          });  
     });
   
 
        $('#map_canvas').gmap3({

        map:{
            options:{
              center:[$("#de_latitud").val(),$("#de_longitud").val()],
               zoom: 15,
               mapTypeId: google.maps.MapTypeId.ROADMAP 
            }
          }, 
         marker:{
            values:[
              {latLng:[$("#de_latitud").val(),$("#de_longitud").val()], data:$("#va_direccion").val()}
            ],
            options:{
              draggable: true
            }
          }
              });   
    console.log($("#de_latitud").val(),$("#de_longitud").val());


	})
</script>