    <div class="span12" style="padding: 10px 0px;">
   
    <div class="control-group span8 "> 
            <form name='form_busqueda'class="form-search" action='/local/index/index/<?php echo $this->in_id;?>' method ="post" style=" margin: 0px;">
                    <div class="span12">
                     <input type='text' name='texto' id="texto" class="span8 " placeholder="Restaurant,Distrito" />
                 <!--    <input type="submit" class="btn" name="submit" value="Buscar"> -->
                    <button type="submit" class="btn" name="submit" style="">Buscar</button>
                    </div>
            </form>
    </div>
     <div class="control-group span4 text-right" >
        <a  class="btn" href="<?php echo $this->basePath();?>/local/index/agregarlocal?id=<?php echo $this->in_id?>">AGREGAR LOCAL</a>
    </div>
    </div>
<div class="row-fluid">
<div class="span12" id="flip-scroll">
<table class="table table-bordered table-hover">
    <thead class="cf">  
        <tr>
          <th >#</th> 
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Horario</th>
<!--            <th>Rango de precio</th>-->
            <th>Direccion</th>
           <!--  <th>Pais</th>
           <th>Departamento</th>
           <th>Provincia</th> -->
            <th>Distrito</th>
            <th>Operaciones</th>
        </tr>
    </thead>
        <?php $count = 1;
    foreach ($this->locales  as $local) :// foreach ($this->paginator as $usuario) :
        ?>
        <tr id="<?php echo $this->escapeHtml($local->in_id); ?>">
            <td><?php echo $count++ ?></td>
            <td><a href="/plato/listar?id=<?php echo $local->in_id?>&res=<?php echo $local->Ta_restaurante_in_id?>"> <?php echo $this->escapeHtml($local->va_nombre); ?> </a> </td>   
            <td><?php echo $this->escapeHtml($local->va_telefono); ?></td>
            <td><?php echo $this->escapeHtml($local->va_horario); ?></td>
<!--            <td><?php echo $this->escapeHtml($local->va_rango_precio); ?></td>-->
            <td><?php echo $this->escapeHtml($local->va_direccion); ?></td>
           <!--  <td><?php echo $this->escapeHtml($local->ch_pais); ?></td>
           <td><?php echo $this->escapeHtml($local->ch_departamento); ?></td>
           <td><?php echo $this->escapeHtml($local->ch_provincia); ?></td> -->
            <td><?php echo $this->escapeHtml($local->ch_distrito); ?></td>
            
             <td><a data-id="<?php echo $this->escapeHtml($local->in_id); ?>" href="/local/index/editarlocal/<?php echo $this->in_id;?>?id=<?php echo $local->in_id;?>" class='modificar btn btn-success'><i class='icon-edit icon-white'></i>Editar </a>
            <a data-id="<?php echo $this->escapeHtml($local->in_id); ?>" href="#" class='eli-lo btn btn-danger'><i class='icon-trash icon-white'></i>Eliminar</a> </td>
        </tr>

<?php endforeach; ?>
    
</table>
     <?php echo (count($this->locales)> 0)?$this->paginationControl($this->locales, 'Sliding', 'platos/index/paginador.phtml',array('variable'=>'/local/index/index/'.$this->in_id.'?')):""; ?>
</div>
</div>
<div class="span4">
  
    <div class="modal small hide fade" id="eli-local" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Confirmación de Eliminación</h3>
        </div>
        <div class="modal-body">
            <p class="error-text"><strong><label id="verlocal"></label></strong></p>

        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            <button class="btn btn-danger" id="delete-local">Eliminar</button>
        </div>
    </div>
    
</div>
