  

<form  accept-charset="utf-8" method="get" class="form-horizontal" id="bubi" autocomplete="on" >
                             
                 <select name="fq" id="fq" class="span2">
                <option value="">seleccione:</option>
                   <?php  foreach ($this->distritos as $distritos) : ?>
                  <option   value="<?php echo $distritos['ch_distrito']; ?>"><?php echo $distritos['ch_distrito']; ?></option>
                  <?php endforeach; ?>
                 </select>
               
                <input id="q" name="q" type="text" placeholder="Ejm: Ceviche, tallarines" value=""/>
                 <button class="verlistado" value="listar" type="submit" ></button>                       
                <a style="margin-left: 10px;text-decoration: underline;"  href="<?php echo $this->basePath(); ?>/application/index/mapa?distrito=<?php echo $_GET['fq']; ?>&plato=<?php echo ($_GET['q']); ?>" >POR MAPA </a>
</form> 
                <a href="#" class="map">aaaaaaaaaaa</a> 
<input id="te" name="q" type="text" placeholder="Ejm: Ceviche, tallarines" value=""/>           

<!--<div id="sa"> <?php echo $this->json ?></div>
<div id="sa"> <input id="ur" type="hidden" value='<?php echo $this->json ?>'/></div>-->
  <div>
        <div id='map' style="height:400px;"></div>
 </div>

 <script type="text/javascript">
   var map;
   $(document).ready(function(){

     var mcOptions = { maxZoom: 14};
     map = new GMaps({
       el: '#map',
       zoom: 12,
        lat: -12.043333,
        lng: -77.028333,
       markerClusterer: function(map) {
   return new MarkerClusterer(map,mcOptions);
 }

     });
     $(".map").on("click",function(){
         var plato=$('#bubi #q').val();
     var dis=$('#bubi #fq').val();
     var url = "http://zf2.pe:8080/application/index/jsonmapasa?distrito=" + dis+ "&plato=" + plato;
     console.log(url);
     $.getJSON( url, function(data) {
             $.each( data.response.docs, function(i, marker) {
                 map.setCenter(marker.latitud,marker.longitud );
                  console.log(marker);
               map.addMarker({
                   lat: marker.latitud,
                   lng: marker.longitud,
                   icon : {
               size : new google.maps.Size(32, 37),
               url : "<?php echo $this->host('static')?>/img/icomap.png"
             },
                   title: marker.restaurante ,
                   infoWindow: {
                           content: marker.name + '</br> <a href=' + 'index.html' +'>ver plato </a>'
                         }

                 });


             });

         });
     });
     
   });
 </script>

