<?php
$this->headTitle('Nosotros:');
?>
<div class="content-left">
	<div class="descrip-product">
		<div class="contenido-static">
			<h2>¿QUÉ ES LISTA DEL SABOR?</h2>
			<p>
				<a href="<?php echo $this->host('ruta')?>">ListaDelSabor.com</a> es una lista de los platos más buscados y mejor recomendados en el Perú, en ella ubicarás sus datos, los restaurantes que lo venden y  su valoración por los comensales. Así mismo datos  del restaurante y ubicación en google maps.
			</p>
			<p class="bold-info">
				<strong>Respondemos a:</strong> …y hoy ¿Qué se te antoja?
			</p>
			<p class="bold-info">
				<strong>¿Cómo lo uso?</strong> <br>
				La forma de uso es simple, son tres pasos:
			</p>
			<ol>
				<li>
					Ingresa el nombre del plato que más te apetece, tipo de plato o nombre del restaurante en el buscador. Ejemplo: “arroz con pato”, “ceviche”, "lomo saltado", etc.
				</li>
				<li>
					Elije de la lista mostrada el plato que más te gusta para ver los detalles del plato, su valoración y los datos del restaurante. También puedes filtrarlos por distrito y ver el resultado de tu búsqueda en un mapa.
				</li>
				<li>
					Disfruta del plato en el lugar que elegiste, valora y comenta para que los demás se enteren.
				</li>
			</ol>
			<p class="bold-info">
				<strong>¿Qué son los "platos destacados"?</strong>
			</p>
			<p>
				En nuestra portada hay una sección llamada "Platos Destacados", estos han sido valorados por los comensales o por nuestro administrador. 
			</p>
			<p>
				También tenemos listas de los "Más Valorados", "Últimos Registrados", entre otras que iremos publicando periódicamente.
			</p>
		</div>
	</div>
</div>