<?php
 $this->headTitle('Terminos:');
?>
<div class="content-left">
	<div class="descrip-product">
		<div class="contenido-static">
			<h2>TÉRMINOS Y CONDICIONES DE USO</h2>
			<p>
				Los términos y condiciones de <a href="<?php echo $this->host('ruta')?>">ListaDelSabor.com</a> rigen tu acceso y uso a los servicios que ofrece la empresa Innovations Systems Group S.A.C. de su sitio web y aplicación móvil ListaDelSabor.com (en adelante el "sitio"). Al acceder, usar e inscribirte al sitio como usuario estás aceptando y dando conformidad a los presentes Términos y Condiciones de Uso. Por tanto, no accedas ni uses el sitio si no estás enteramente de acuerdo.
			</p>
			<p class="bold-info">
				<strong>Cambios en las condiciones del servicio</strong>
			</p>
			<p>
				Podemos modificar las condiciones en el momento que consideremos oportuno. Entiendes que aceptas las condiciones que rigen en el momento de tu acceso.
			</p>
			<p class="bold-info">
				<strong>Uso del sitio</strong>
			</p>
			<p>
				Puedes usar el sitio sujeto a las condiciones del servicio.
			</p>
			<p>
				El sitio puede ser modificado, actualizado, interrumpido, suspendido o eliminado en cualquier momento sin previo aviso.
				El registro como usuario será mediante tu nombre y un correo electrónico, mediante el cual puedes comentar o valorar un plato/restaurante. Es de tu responsabilidad usar tu propio nombre y cuenta de correo para reforzar tu credibilidad. Nos reservamos el derecho de cerrar tu cuenta en cualquier momento.
			</p>
			<p>
				Al crear una cuenta aceptas recibir comunicaciones del sitio.
			</p>
			<p class="bold-info">
				<strong>Comentarios</strong>
			</p>
			<p>
				Los comentarios vertidos sobre los platos/restaurantes no son asumidos como nuestra responsabilidad. El sitio podrá rechazarlos o filtrarlos cuando los considere "no adecuados" o cuando sean denunciados.
			</p>
			<p class="bold-info">
				<strong>Información</strong>
			</p>
			<p>
				La información mostrada de los platos/restaurantes es obtenida del propio restaurant o de información publicada en la web.
			</p>
		</div>
	</div>
</div>
